# -*- coding: utf-8 -*-
"""2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/105v5_KAraoPU9jU74RjdsBNxLrNSpu0Z

# E19CSE002

##Importing File and creating two lists
"""

import os
import numpy as np
path=('drive/MyDrive/Colab Notebooks/AI-ML/Lab2_2/archive')
data=[]#for storing entire text
all_files = os.listdir(path)
for fle in all_files:
    if fle.endswith('.txt'):
      with open(os.path.join(path, fle)) as f:
        text=np.loadtxt(f, dtype='str')
        data.append(text)
  
filenames=[x for x in all_files]#for storing file names

print(filenames)
print()
data[0][0]='He@$llo!'
data[0][1]='shabd'
print(data[0])

"""## Removing Special Characters"""

import re

for i in range(len(data)):
  for j in range(len(data[i])):
    data[i][j]=re.sub('\W+','',data[i][j])
  
print(data[0][0:30])

"""## Lowering all words"""

for i in range(len(data)):
  for j in range(len(data[i])):
    data[i][j]=data[i][j].lower()
print(data[0][:30])

"""## Importing NLTK Library

"""

import nltk
nltk.download('words')

words = set(nltk.corpus.words.words())

"""## Removing Non-English Words"""

final=[]
for i in range(len(data)):
  temp=[]
  for j in range(len(data[i])):
    if data[i][j] in words:
      temp.append(data[i][j])
  final.append(temp)

print(final[0][:10])

"""## Implementing the frequency search
Part - 1: thank

"""

search=input("Enter the Keyword : ")

freq_list=[]
for i in range(len(final)):
  freq_in_file=0
  for j in final[i]:
    if(j==search):
      freq_in_file+=1
  freq_list.append(freq_in_file)

print()
finaldict=dict(zip(filenames,freq_list))
for i in sorted(finaldict , key=finaldict.get, reverse=True):
  print(i,"  :   ", finaldict[i])

"""Part-2: very"""

search=input("Enter the Keyword : ")

freq_list=[]
for i in range(len(final)):
  freq_in_file=0
  for j in final[i]:
    if(j==search):
      freq_in_file+=1
  freq_list.append(freq_in_file)

print()
finaldict=dict(zip(filenames,freq_list))
for i in sorted(finaldict , key=finaldict.get, reverse=True):
  print(i,"  :   ", finaldict[i])

"""Part-3: people

"""

search=input("Enter the Keyword : ")

freq_list=[]
for i in range(len(final)):
  freq_in_file=0
  for j in final[i]:
    if(j==search):
      freq_in_file+=1
  freq_list.append(freq_in_file)

print()
finaldict=dict(zip(filenames,freq_list))
for i in sorted(finaldict , key=finaldict.get, reverse=True):
  print(i,"  :   ", finaldict[i])